name: CI

on:
  push:
    branches:
      - features/**
      - hotfix/**
    paths:
      - projects/ng-azure-maps/**
      - .github/**
  pull_request:
    branches:
      - develop
      - main
    paths:
      - projects/ng-azure-maps/**
      - .github/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 8
    - name: npm install
      run: npm install
    - name: Build
      run: npm run build ng-azure-maps --prod

